services:
  python-backend:
    build: .
    container_name: cotizador-construccion-python
    working_dir: /app
    command: python -m uvicorn backend-python.app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/backend-python
    restart: unless-stopped

  node-backend:
    build: 
      context: .
      dockerfile: Dockerfile.node
    container_name: cotizador-construccion-node
    working_dir: /app
    command: npm start
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PY_SERVICE_URL=http://python-backend:8000
    depends_on:
      - python-backend
    restart: unless-stopped
